### ISSUE TITLE
change badges from stable to dynamic from gist.

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Tai-Shang-DAO-NFT-Manager#9]
money: `300R`

> Gist File:
> https://gist.github.com/leeduckgo/9c765cdeb324685d0d0c0099ba433a19

> Documentation:
> https://docs.github.com/en/rest/gists/gists

**Comment by itherunder** [comment]
here🙋🏻

**Comment by itherunder** [comment]
finished [here](https://github.com/WeLightProject/Tai-Shang-DAO-NFT-Manager/pull/10)🙌
